const quotes = [
  { quote: "Dans 20 ans, vous serez plus déçu par les choses que vous n’avez pas faites que par celles que vous avez faites. Alors sortez des sentiers battus. Mettez les voiles. Explorez. Rêvez. Découvrez.", author: "Mark Twain" },
  { quote: "En suivant le chemin qui s’appelle plus tard, nous arrivons sur la place qui s’appelle jamais.", author: "Sénèque" },
  { quote: "La discipline est le pont entre les objectifs et leur réalisation.", author: "Jim Rohn" },
  { quote: "Le pessimisme est affaire d’humeur ; l’optimisme est affaire de volonté.", author: "Alain (Emile Auguste Chartier)" },
  { quote: "Il n’y a pas de futur, pas de passé. Il n’y a que le présent.", author: "Hector Garcia Puigcerver, Ikigai: Le secret japonais pour une vie longue et heureuse" },
  { quote: "Vous devez apprendre des erreurs des autres car vous ne pourrez vivre assez longtemps pour toutes les faire vous-mêmes.", author: "Anonyme" },
  { quote: "Tout peut être pris chez un homme, sauf une chose: la dernière des libertés humaines: choisir son attitude dans toutes les circonstances, choisir sa propre voie.", author: "Hector Garcia Puigcerver, Ikigai: Le secret japonais pour une vie longue et heureuse" },
  { quote: "Ce n’est pas la force, mais la persévérance, qui fait les grandes œuvres.", author: "Samuel Johnson" },
  { quote: "Accepter l’idée de la défaite c’est être déjà vaincu.", author: "Général Foch" },
  { quote: "Ce qui va sans le dire va encore mieux en le disant.", author: "Talleyrand" },
  { quote: "Notre caractère est fait d’habitude : qui sème une pensée récolte une action. Qui sème une action récolte une habitude. Qui sème une habitude récolte un caractère. Qui sème un caractère, récolte un destin.", author: "Stephen Covey" },
  { quote: "N'attendez pas. Le moment parfait n'existe pas.", author: "Napoléon Hill" },
  { quote: "Pense, crois, rêve et ose.", author: "Walt Disney" },
  { quote: "La vraie vie est si souvent celle qu’on ne vit pas.", author: "Oscar Wilde" },
  { quote: "Quand vous cherchez des gens à recruter, vous devez rechercher trois qualités : l’intégrité, l’intelligence et l’énergie. Et s’ils ne possèdent pas la première, les deux autres vous tueront.", author: "Warren Buffett" },
  { quote: "Vous devez être le changement que vous voulez voir dans le monde.", author: "Mahatma Gandhi" },
  { quote: "Seuls ceux qui sont suffisamment fous pour penser qu’ils peuvent changer le monde y arrivent.", author: "Steve Jobs" },
  { quote: "La vie n’est jamais rendue insupportable par les circonstances, mais par un manque de sens et d’intérêt.", author: "Viktor Frankl" },
  { quote: "Notre entreprise ne consiste pas à être devant qui que ce soit mais à être devant nous-mêmes.", author: "E. Joseph Cossman" },
  { quote: "On peut convaincre les autres par ses propres raisons, mais on ne les persuade que par les leurs.", author: "Alphonse Daudet" },
  { quote: "Un bon croquis vaut mieux qu’un long discours.", author: "Napoléon Bonaparte" },
  { quote: "Quand deux sage confrontent leurs idées, ils en produisent de meilleures; le jaune et le rouge mélangés produisent une autre couleur.", author: "Proverbe tibétain" },
  { quote: "Autant le succès que l’échec sont en grande partie les résultats d’habitude.", author: "Napoleon Hill" },
  { quote: "La persévérance est la clé du succès.", author: "Charles Chaplin" },
  { quote: "Une période d’échec est un moment rêvé pour semer les graines du succès.", author: "Paramahansa Yogananda" },
  { quote: "Faites du mieux que vous pouvez jusqu'à ce que vous sachiez mieux. Quand vous savez mieux, faites mieux.", author: "Maya Angelou" },
  { quote: "La plus adroite façon de plaire est de demander des conseils.", author: "Octave Pirmez" },
  { quote: "Trop d’entre nous ne vivent pas leurs rêves car nous vivons nos peurs.", author: "Les Brown" },
  { quote: "Les opportunités sont comme les autobus, il y en a toujours un autre qui arrive.", author: "Richard Branson" },
  { quote: "Vous pouvez tromper tout le monde une fois, quelques-uns souvent, mais vous ne pouvez tromper tout le monde tout le temps.", author: "Abraham Lincoln." },
  { quote: "Vis comme si tu devais mourir demain. Apprends comme si tu devais vivre toujours.", author: "Gandhi" },
  { quote: "Si vous commencez avec rien et que vous finissez avec rien, vous avez donc rien à perdre.", author: "Michael Dunlop" },
  { quote: "La peur n’est pas réelle. C’est un produit de la pensée que vous créez. Ne vous méprenez pas. Le danger est très réel. Mais la peur est un choix.", author: "Will Smith" },
  { quote: "C’est toujours l’impatience de gagner qui fait perdre.", author: "Louis XIV" },
  { quote: "Les pauvres ont de grandes télés, les riches ont de grandes bibliothèques", author: "Jim Rohn" },
  { quote: "L’homme a deux oreilles et une bouche pour écouter deux fois plus qu’il ne parle.", author: "Alphonse Allais" },
  { quote: "Si vous désirez vraiment faire quelque chose, vous trouverez un moyen. Sinon, vous trouverez une excuse.", author: "Jim Rohn" },
  { quote: "Le véritable voyage ne consiste pas à chercher de nouveaux paysages, mais à avoir de nouveaux yeux.", author: "Marcel Proust" },
  { quote: "Dès l’instant où vous aurez foi en vous-même, vous saurez comment vivre.", author: "Goethe « Jamais jamais jamais. N’abandonnez jamais." },
  { quote: "Commencez maintenant, pas demain. Demain est une excuse de perdant.", author: "Andrew Fashion" },
  { quote: "La meilleure façon de prédire l'avenir est de le créer.", author: "Peter Drucker" },
  { quote: "Le sens de la vie est de trouver votre don. Le but de la vie est de le partager.", author: "William Shakespeare" },
  { quote: "Avec trop on se perd. Avec moins on se trouve.", author: "Tchouang Tseu" },
  { quote: "Entreprendre, c’est  sauter d’une falaise et construire un plan pendant la descente.", author: "Reid Hoffman" },
  { quote: "Les paroles sincères ne sont pas élégantes ; les paroles élégantes ne sont pas sincères.", author: "Lao Tseu" },
  { quote: "Lorsque la passion est forte, il n’est de digue ni de mur que son courant emporte.", author: "Victor Hugo" },
  { quote: "Ne renoncez jamais à un rêve juste à cause du temps qu’il faudra pour l’accomplir. Le temps passera de toute façon.", author: "Earl Nightingale" },
  { quote: "Le succès c’est tomber sept fois, se relever huit.", author: "Proverbe japonais" },
  { quote: "Avoir un objectif clair et concret", author: "Hector Garcia Puigcerver, Ikigai: le secret japonais d’une vie longue et heureuse" },
  { quote: "Ne prend la parole que si ce que tu vas dire est plus fort que le silence.", author: "Euripide" },
  { quote: "Là se trouve la semence d’un avantage équivalent dans chaque adversité. Dans chaque défaite est une leçon de vous montrer comment gagner la victoire la prochaine fois.", author: "Robert Collier" },
  { quote: "Un homme doit être assez grand pour admettre ses erreurs, assez intelligent pour apprendre de celles-ci et assez fort pour les corriger.", author: "John C. Maxwell" },
  { quote: "Ne négociez pas avec vos peurs. Mais n’ayez pas peur de négocier.", author: "John F. Kennedy" },
  { quote: "On a deux vies. La deuxième commence quand on réalise qu’on n’en a qu’une.", author: "Confucius" },
  { quote: "Le seul homme à ne jamais faire d’erreurs est celui qui ne fait rien.", author: "Theodore Roosevelt" },
  { quote: "L’Homme meurt une première fois à l’âge où il perd l’enthousiasme.", author: "Honoré de Balzac" },
  { quote: "Si vous ne croyez pas en la connaissance, essayez donc l’ignorance.", author: "Abraham Lincoln" },
  { quote: "Mon objectif n’a jamais été de créer une entreprise. Mais de bâtir quelque chose susceptible de changer le monde", author: "Mark Zuckerberg" },
  { quote: "Pour réussir, votre désir de réussite doit être plus grand que votre peur de l’échec.", author: "Bill Cosby" },
  { quote: "Celui qui pose une question risque de passer pour un sot. Celui qui n’en pose pas est sûr de le rester.", author: "Confucius" },
  { quote: "Apprenez des erreurs des autres. Vous ne vivrez pas assez longtemps pour toutes les faire vous-même.", author: "Eleanor Roosevelt" },
  { quote: "Pour ce qui est de l’avenir, il ne s’agit pas de le prévoir mais de le rendre possible.", author: "Antoine de Saint-Exupéry" },
  { quote: "Il y a des jours, des mois, des années interminables où il ne se passe presque rien. Il y a des minutes et des secondes qui contiennent tout un monde.", author: "Jean d’Ormesson" },
  { quote: "Il n'y a qu'une façon d'échouer, c'est d'abandonner avant d'avoir réussi.", author: "Georges Clemenceau" },
  { quote: "Je voulais vivre intensément et sucer la moelle de la vie. Et ne pas, quand je viendrai à mourir, découvrir que je n’aurai pas vécu.", author: "Henry-David Thoreau" },
  { quote: "Fréquentez les gens qui ont quelque chose de valable à partager avec vous et leur impact restera significatif sur votre vie bien longtemps après leur mort.", author: "Jim Rohn" },
  { quote: "La chose la plus précieuse que vous pouvez faire est une erreur. Vous ne pouvez rien apprendre en étant parfait.", author: "Adam Osborne" },
  { quote: "Tout ce que vous êtes ou deviendrez est le résultat de l’utilisation de votre esprit.", author: "Napoleon Hill" },
  { quote: "Les gens pensent que l’innovation c’est d’avoir une bonne idée, mais l’innovation consiste en grande partie à agir rapidement et à essayer beaucoup de choses.", author: "Mark Zuckerberg" },
  { quote: "La vie est trop courte pour passer du temps avec des gens qui n’ont pas d’envie.", author: "Jeff Bezos" },
  { quote: "Le meilleur moment pour planter un arbre était il y a 20 ans. Le Deuxième meilleur moment est maintenant.", author: "Proverbe chinois" },
  { quote: "La vie mettra des pierres sur ta route. A toi de décider d’en faire des murs ou des ponts.", author: "Auteur Inconnu" },
  { quote: "Le succès n'est pas la clé du bonheur. Le bonheur est la clé du succès. Si vous aimez ce que vous faites, vous réussirez.", author: "Albert Schweitzer" },
  { quote: "Quand on a besoin d’innover, il faut collaborer.", author: "Marissa Mayer" },
  { quote: "Ce qui noie quelqu’un, ce n’est pas le plongeon, mais le fait de rester sous l’eau.", author: "Paulo Coelho" },
  { quote: "Si quelqu’un vous offre une opportunité incroyable mais que vous n’êtes pas sûr de pouvoir le faire, acceptez… puis apprenez à le faire plus tard.", author: "Richard Branson" },
  { quote: "Rester immobile ne sert à rien. Il faut choisir entre progresser ou régresser. Allons donc de l’avant et le sourire aux lèvres.", author: "Baden-Powell" },
  { quote: "Ce n’est pas le vent qui décide de votre destination, c’est l’orientation que vous donnez à votre voile ; le vent est le même pour tous.", author: "Jim Rohn" },
  { quote: "Le succès c’est la capacité à utiliser votre potentiel au maximum.", author: "Zig Ziglar" },
  { quote: "Le succès : 1% d’inspiration et 99% de transpiration.", author: "Thomas Edison" },
  { quote: "Le plus grand bien que nous faisons aux autres hommes n’est pas de leur communiquer notre richesse, mais de leur révéler la leur.", author: "Louis Lavelle" },
  { quote: "Chaque journée est une nouvelle chance de changer votre vie.", author: "Auteur inconnu" },
  { quote: "Le bonheur n'est pas quelque chose de prêt à l'emploi. Il vient de vos propres actions.", author: "Dalaï Lama" },
  { quote: "Le secret d’ennuyer est celui de tout dire.", author: "Voltaire" },
  { quote: "La vie peut toujours évoluer tant qu’on continue d’apprendre.", author: "Charles Lamb" },
  { quote: "Je choisirai un homme paresseux pour faire un travail difficile parce qu’il trouvera un moyen facile de le faire.", author: "Bill Gates" },
  { quote: "Il est des moments où il faut choisir entre vivre sa propre vie pleinement, entièrement, complètement, ou traîner l’existence dégradante, creuse et fausse que le monde, dans son hypocrisie, nous impose.", author: "Oscar Wilde" },
  { quote: "Ne comptez pas les jours, faites que les jours comptent.", author: "Muhammad Ali" },
  { quote: "Si vous pouvez le rêver, vous pouvez le faire.", author: "Walt Disney" },
  { quote: "La vie est un défi à relever, un bonheur à mériter, une aventure à tenter.", author: "Mère Teresa" },
  { quote: "Si vous créez une excellente expérience client, les clients en parleront. Le bouche à oreille est un outil très puissant.", author: "Jeff Bezos" },
  { quote: "Le secret des affaires est de savoir quelque chose que personne d’autre ne sait.", author: "Aristote Onassis" },
  { quote: "Le vrai voyageur n'a pas de plan établi et n'a pas l'intention d'arriver.", author: "Lao Tseu" },
  { quote: "Si vous ne courez pas après ce que vous voulez, vous ne l’aurez jamais. Si vous ne demandez pas, la réponse sera toujours non. Si vous ne faites pas un pas en avant, vous restez toujours au même endroit.", author: "Nora Roberts" },
  { quote: "Transmettre ce n’est pas remplir un vase, c’est allumer un feu.", author: "Montaigne" },
  { quote: "Les hommes sont malheureux parce qu’ils ne réalisent pas les rêves qu’ils ont.", author: "Jacques Brel" },
  { quote: "La meilleure manière de se lancer, c’est d’arrêter de parler et commencer à agir.", author: "Walt Disney" },
  { quote: "Tu dois devenir l’homme que tu es. Fais ce que toi seul peux faire. Deviens sans cesse celui que tu es, sois le maître et le sculpteur de toi-même.", author: "Friedrich Nietzsche" },
  { quote: "Ce sont les questions, plus que les réponses qui montrent l’étendue de l’esprit.", author: "Montaigne" },
  { quote: "Tout ce que vous pouvez imaginer est réel.", author: "Pablo Picasso" },
  { quote: "La vie est comme une bicyclette, il faut avancer pour ne pas perdre l’équilibre.", author: "Albert Einstein" },
  { quote: "Le courage est la première des qualités humaines, car elle garantit toutes les autres.", author: "Aristote" },
  { quote: "Le plus grand danger pour la plupart d'entre nous n'est pas que notre objectif soit trop élevé et que nous le manquions, mais qu'il soit trop bas et que nous l'atteignions.", author: "Michel-Ange" },
  { quote: "Un voyage de mille lieues commence toujours par un premier pas.", author: "Lao Tseu" },
  { quote: "Être conscient de son ignorance est le premier pas vers la connaissance.", author: "Benjamin Disrael" },
  { quote: "La vraie générosité envers l’avenir consiste à tout donner au présent.", author: "Albert Camus" },
  { quote: "Il n’y a qu’un succès : être en mesure de vivre votre vie telle que vous le voulez.", author: "Christopher Morley" },
  { quote: "Il faut savoir ce que l’on veut. Quand on le sait, il faut avoir le courage de le dire ; quand on le dit, il faut avoir le courage de le faire.", author: "Georges Clemenceau" },
  { quote: "Ne devenez pas l’ami des gens avec qui vous êtes à l’aise. Devenez l’ami de gens qui vous oblige à vous dépasser.", author: "Christopher Morley" },
  { quote: "La vie est un mystère qu'il faut vivre, et non un problème à résoudre.", author: "Gandhi" },
  { quote: "Les individus qui réussissent sont ceux qui savent mobiliser toutes leurs ressources mentales et physiques sur un objectif.", author: "Anthony Robbins" },
  { quote: "J’ai décidé d’être heureux parce que c’est bon pour la santé.", author: "Voltaire" },
  { quote: "Ce n’est pas le plus fort de l’espèce qui survit, ni le plus intelligent, mais le plus apte au changement.", author: "Charles Darwin" },
  { quote: "La clé de la vie est d’être heureux avec ou sans argent.", author: "Robert T. Kiyosaki" },
  { quote: "Nous sommes ce que nous faisons de manière répétée. L’excellence n’est donc pas un acte mais une habitude.", author: "Aristote" },
  { quote: "Nous avons autant besoin de raisons de vivre que de quoi vivre.", author: "Abbé Pierre" },
  { quote: "L’art de convaincre consiste à dire trois fois la même chose : on dit ce que l’on va dire, on le dit, on dit ce que l’on a dit.", author: "Platon" },
  { quote: "J’ai fait le constat suivant : tout ce que nous ferons pour aider un client à mieux réussir se traduira inexorablement par une récompense financière pour nous.", author: "Jack Welch" },
  { quote: "Le travail acharné bat le talent quand le talent ne travaille pas.", author: "Tim Notke" },
  { quote: "Une promesse sans preuve, c’est une poignée sans valise.", author: "Jean Saint-Mleux" },
  { quote: "Votre réseau est composé de gens qui veulent vous aider et que vous voulez aider, et c’est très puissant.", author: "Reid Hoffman" },
  { quote: "Malheur à celui qui ne sait pas reconnaître son prochain à sa poignée de main.", author: "Théodore Roosevelt." },
  { quote: "La logique vous mène de A à B. L’imagination vous mènera partout.", author: "Albert Einstein" },
  { quote: "Quand tout semble être contre vous, souvenez-vous que l’avion décolle face au vent, et non avec lui.", author: "Henry Ford" },
  { quote: "La pensée positive vous permettra de tout faire d’une meilleure façon que la pensée négative.", author: "Zig Ziglar" },
  { quote: "Hâte-toi de bien vivre et songe que chaque jour est à lui seul une vie.", author: "Sénèque" },
  { quote: "Ils ne savaient pas que c’était impossible, alors ils l’ont fait.", author: "Mark Twain" },
  { quote: "Tout est relatif. Mais il est une chose absolue dans notre monde. C’est l’humour.", author: "Albert Einstein" },
  { quote: "On a toujours le choix. On est même la somme de ses choix.", author: "Joseph O’ Connor" },
  { quote: "La persuasion est plus efficace que la force.", author: "Ésope" },
  { quote: "Entourez-vous seulement de gens qui vont vous tirer vers le haut.", author: "Oprah Winfrey" },
  { quote: "Agissez comme s'il était impossible d'échouer.", author: "Winston Churchill" },
  { quote: "Ce sont les gens les plus carrés en affaires qui les mènent souvent le plus rondement.", author: "Pierre Dac" },
  { quote: "Un homme supérieur est modeste dans son discours, mais se surpasse dans ses actions.", author: "Confucius" },
  { quote: "Vos clients les plus mécontents constituent votre meilleure source d’apprentissage.", author: "Bill Gates" },
  { quote: "Un objectif est un rêve doté d’une échéance.", author: "Napoléon Hill" },
  { quote: "La motivation est ce qui vous permet de vous lancer, l’habitude ce qui vous permet de continuer.", author: "Jim Rohn" },
  { quote: "Un bon commerçant doit cacher soigneusement sa marchandise et faire comme s’il n’avait rien.", author: "Proverbe chinois" },
  { quote: "Le moment présent a un avantage sur tous les autres : il nous appartient.", author: "Charles Caleb Colton" },
  { quote: "Ne rêvez pas votre vie, vivez vos rêves.", author: "Auteur inconnu" },
  { quote: "Dans nos ateliers, nous réalisons des robes ; dans nos salons nous vendons de l’espoir.", author: "Christian Dior" },
  { quote: "Exige beaucoup de toi-même et attends peu des autres. Ainsi beaucoup d’ennuis te seront épargnés.", author: "Confucius" },
  { quote: "En te levant le matin, rappelle-toi combien précieux est le privilège de vivre, de respirer, d’être heureux.", author: "Marc Aurèle" },
  { quote: "Quand on voyage vers un objectif, il est très important de prêter attention au chemin. C’est toujours le chemin qui nous enseigne la meilleure façon d’y parvenir, et il nous enrichit à mesure que nous le parcourons.", author: "Paulo Coelho" },
  { quote: "Rêver grand et oser échouer.", author: "Normand Vaughan" },
  { quote: "La plus grande gloire n'est pas de ne jamais tomber, mais de se relever à chaque chute.", author: "Confucius" },
  { quote: "Savoir écouter, c’est posséder, outre le sien, le cerveau des autres.", author: "Léonard de Vinci" },
  { quote: "La vie est composée pour 10% par ce qu’il vous arrive et 90% par comment vous y réagissez.", author: "Charles Swindol" },
  { quote: "Un objectif bien défini est à moitié atteint.", author: "Abraham Lincoln" },
  { quote: "Celui qui ne sait pas où il va se retrouve ailleurs.", author: "Robespierre" },
  { quote: "Qu’est-ce qui conditionne la réussite ? La capacité à soutenir un effort continu.", author: "Henry Ford" },
  { quote: "La vie, ce n’est pas d’attendre que les orages passent, c’est d’apprendre à danser sous la pluie.", author: "Sénèque" },
  { quote: "La chose la plus importante en communication, c’est d’entendre ce qui n’est pas dit.", author: "Peter Drucker" },
  { quote: "La maturité de l’homme, c’est d’avoir retrouvé le sérieux qu’on avait au jeu quand on était enfant.", author: "Friedrich Nietzsche" },
  { quote: "Sachez écouter, et soyez sûr que le silence produit souvent le même effet que la science.", author: "Napoléon Bonaparte" },
  { quote: "Ne dites plus que vous n’avez pas assez de temps. Vous avez exactement le même nombre d’heures par jour que Helen Keller, Louis Pasteur, Michelangelo, Mère Teresa, Leonardo de Vinci, Thomas Jefferson et Albert Einstein.", author: "H. Jackson Brown, Jr" },
  { quote: "L’imagination est tout. C’est un avant goût de ce que la vie nous réserve.", author: "Albert Einstein" },
  { quote: "Il y a plus de courage que de talent dans la plupart des réussites.", author: "Félix Leclerc" },
  { quote: "Ne démarrez pas une entreprise à moins que ce ne soit une obsession et quelque chose que vous aimez. Si vous avez une stratégie de sortie, ce n’est pas une obsession.", author: "Mark Cuban" },
  { quote: "Il n’y a qu’une seule façon d’éviter les critiques ; Ne dis rien, ne fais rien, ne sois rien.", author: "Aristote" },
  { quote: "La seule peur qui puisse empêcher un rêve d’aboutir, c’est la peur d’échouer !", author: "Paulo Coelho" },
  { quote: "L’art du compromis consiste à partager un gâteau de telle sorte que chacun croie avoir la plus grosse part.", author: "Henri Kissinger" },
  { quote: "L'échec est seulement l'opportunité de recommencer de manière plus intelligente.", author: "Henry Ford" },
  { quote: "Le bon général a gagné la bataille avant de l’engager.", author: "Sun Tzu" },
  { quote: "Le voyage de mille lieues commence par un pas.", author: "Lao Tseu" },
  { quote: "Parler est un besoin, écouter est un art.", author: "Johann Wolfgang Von Goethe" },
  { quote: "Toute connaissance commence par les sentiments.", author: "Léonard de Vinci" },
  { quote: "Si vous regardez où tout le monde regarde, vous regardez au mauvais endroit.", author: "Mark Cuban" },
  { quote: "N’évalue pas chaque jour qui passe par ce que tu récoltes mais plutôt par ce que tu sèmes.", author: "Robert Louis Stevenson" },
  { quote: "Les livres vous permettent d’explorer pleinement un sujet et de vous immerger plus profondément que la plupart des médias aujourd’hui.", author: "Mark Zuckerberg" },
  { quote: "Chacun sait que dans le train de l’entreprise, le vendeur est la locomotive.", author: "Winston Churchill" },
  { quote: "Pour deux heures de travail, vous voulez deux cent mille francs ? Non je les veux pour une vie d’expérience.", author: "Pablo Picasso" },
  { quote: "Le sens de la vie est la plus pressante des questions.", author: "Albert Camus" },
  { quote: "L’homme qui travaille plus que ce qu’il n’est payé sera bientôt payé plus qu’il travaille.", author: "Napoleon Hil" },
  { quote: "Le succès c’est d’aller d’échec en échec sans perdre son enthousiasme.", author: "Winston Churchill" },
  { quote: "La fortune sourit aux audacieux.", author: "Virgile" },
  { quote: "L’enthousiasme est une maladie contagieuse.", author: "Voltaire" },
  { quote: "Le sens de la vie : le but de tout est d’évoluer.", author: "Bernard Werber" },
  { quote: "Il ne faut pas attendre l’idée géniale ou le produit parfait. Procédez par ajustements, jusqu’à fournir un service dont vous pouvez être fier. N’attendez pas demain et lancez-vous aujourd’hui.", author: "Xavier Niel" },
  { quote: "Si les gens savaient combien je travaille dur pour acquérir ma maîtrise, ça ne leur semblerait pas, après tout, tellement merveilleux.", author: "Michel-Ange" },
  { quote: "Une règle simple pour vraiment changer les choses, c’est de commencer toujours par le plus simple, et non par le plus difficile. Parce que c’est la meilleure manière de progresser rapidement.", author: "Mark Zuckerberg" },
  { quote: "J’ai toujours travaillé très dur, et plus dur je travaille, plus chanceux je deviens.", author: "Alan Bond" },
  { quote: "Les réussites spectaculaires sont toujours précédées de préparations peu spectaculaires.", author: "Chamfort" },
  { quote: "Un crétin qui marche va plus loin qu’un intello assis.", author: "Michel Audiard" },
  { quote: "Ne jugez pas chaque jour à la récolte que vous faites mais aux graines que vous plantez.", author: "Robert Louis Stevenson" },
  { quote: "Là où vos talents et les besoins du monde se rencontrent, là se trouve votre vocation.", author: "Aristote." },
  { quote: "Si tu ne comprends pas ton business en détail, tu te diriges vers l’échec.", author: "Jeff Bezos" },
  { quote: "Certaines personnes voient les choses comme elles sont et se demandent : Pourquoi ? Moi je vois les choses comme elles pourraient être et je me dis : Pourquoi pas ?", author: "John Fitzgerald Kennedy" },
  { quote: "On n’a jamais deux occasions de faire une bonne première impression.", author: "Anonyme" },
  { quote: "Parle est le privilège de la connaissance, écouter est le privilège de la sagesse.", author: "Plutarque" },
  { quote: "Ne cherchez pas des clients pour vos produits, mais faites des produits pour vos clients", author: "Seth Godin" },
  { quote: "Qui parle sème, qui écoute récolte.", author: "Pythagore" },
  { quote: "Il y a deux façons de penser. L’une est de croire que les miracles n’existent pas. L’autre est de croire que chaque chose est un miracle.", author: "Albert Einstein" },
  { quote: "Si vous regardez avec attention, la plupart des succès obtenus du jour au lendemain prennent beaucoup de temps.", author: "Steve Jobs" },
  { quote: "La chance sourit à ceux qui décident d’en avoir et qui agissent dans ce sens.", author: "Philippe Gabilliet" },
  { quote: "Traitez vos employés exactement tel que vous aimeriez qu’ils traitent vos meilleurs clients.", author: "Stephen R. Covey" },
  { quote: "Ne t’inquiète pas de l’échec. Inquiète-toi de ce que tu manques si tu n’essayes même pas.", author: "Jack Canfield" },
  { quote: "Si vous gagnez sans progresser, vous ne serez jamais champion.", author: "John McEnroe" },
  { quote: "Si la connaissance créé parfois des problèmes, ce n’est pas l’ignorance qui permet de les résoudre.", author: "Isaac Asimov" },
  { quote: "La seule façon de faire du bon travail est d’aimer ce que vous faites. Si vous n’avez pas encore trouvé, continuez à chercher.", author: "Steve Jobs" },
  { quote: "Se libérer de la peur, c’est le premier pas, la clef du changement.", author: "Antonella Verdiani" },
  { quote: "Si vous pensez que l’aventure est dangereuse, essayez la routine, elle est mortelle.", author: "Paulo Coelho" },
  { quote: "Contentons-nous de faire réfléchir, c’est le plus sûr moyen de convaincre.", author: "George Braque" },
  { quote: "L’imagination est plus importante que le savoir.", author: "Albert Einstein" },
  { quote: "Tenez-vous loin des gens qui tentent de diminuer vos ambitions. Les  petites  personnes font toujours cela, mais les  grandes , elles, vous font sentir que vous pouvez également devenir génial.", author: "Mark Twain" },
  { quote: "Si tu ignores ce pour quoi tu vis, c’est que tu n’as pas encore vécu.", author: "Rabbin Noa’h Weinberg" },
  { quote: "Notre plus grande gloire n’est pas de ne jamais tomber, mais de se relever à chaque fois que l’on tombe.", author: "Napoléon Bonaparte" },
  { quote: "Le cœur connait la bonne réponse.", author: "Deepak Chopra" },
  { quote: "Tout objectif flou conduit irrémédiablement à une connerie précise.", author: "Anonyme" },
  { quote: "Je savais que si j’échouais, je ne le regretterai pas, mais je savais que la seule chose que je pourrais regretter était de ne pas essayer.", author: "Jeff Bezos" },
  { quote: "Les grandes réalisations sont toujours précédées par de grandes pensées.", author: "Steve Jobs" },
  { quote: "Je crois beaucoup en la chance. D’ailleurs, je constate que plus je travaille et plus la chance me sourit.", author: "Thomas Jefferson" },
  { quote: "Ne laissez pas les choses que vous êtes incapable de faire nuire à celles que vous pouvez accomplir.", author: "John Wooden" },
  { quote: "Appréciez d’échouer, et apprenez de l’échec, car on n’apprend rien de ses succès.", author: "James Dyson" },
  { quote: "Croyez que vous pouvez et vous serez déjà à mi-chemin.", author: "Theodore Roosevelt" },
  { quote: "Ce n'est pas l'étoile qui fait le navire, mais l'effort des marins.", author: "Proverbe africain" },
  { quote: "Celui qui est le maître de lui-même est plus grand que celui qui est le maître du monde.", author: "Bouddha" },
  { quote: "Il n’y a pas plus belle aventure au monde que de vivre la vie de vos rêves.", author: "Oprah Winfrey" },
  { quote: "Dans l’histoire d’une vie, on n’a jamais qu’un seul problème à résoudre, celui qui donne sens à notre existence et impose un style à nos relations.", author: "Boris Cyrulnik" },
  { quote: "Une fausse note jouée avec timidité est une fausse note, une fausse note jouée avec conviction est une interprétation.", author: "Claude Luter" },
  { quote: "Croyez en vous et tout sera possible.", author: "Audrey Hepburn" },
  { quote: "L’important n’est pas ce qu’on a fait de moi, mais ce que je fais moi-même de ce qu’on a fait de moi.", author: "Jean-Paul Sartre" },
  { quote: "Si vous ne pouvez pas voler, courrez alors. Si vous ne pouvez pas courir, marchez alors. Si vous ne pouvez pas marcher, rampez alors, mais quoi que vous fassiez, il faudra avancer.", author: "Martin Luther King" },
  { quote: "Il y a de la place au soleil pour tout le monde, surtout quand tout le monde veut rester à l’ombre.", author: "Jules Renard" },
  { quote: "Ce n’est pas parce que les choses sont difficiles que nous n’osons pas les faire, c’est parce que nous n’osons pas les faire qu’elles sont difficiles.", author: "Sénèque" },
  { quote: "Les limites ne vivent que dans notre esprit.", author: "Bob Proctor" },
  { quote: "Je ne perd jamais. Soit je gagne, soit j’apprends.", author: "Nelson Mandela" },
  { quote: "La seule limite à notre épanouissement de demain sera nos doutes d'aujourd'hui.", author: "Franklin D. Roosevelt" },
  { quote: "Encore faut-il pousser une porte pour savoir qu’elle nous est close.", author: "Montaigne" },
  { quote: "La vie nous donne toujours une autre chance, elle se nomme : maintenant.", author: "Stéphane Robin" },
  { quote: "Le bonheur n’est pas quelque chose que vous reportez pour l’avenir, c’est quelque chose que vous concevez pour le moment.", author: "Jim Rohn" },
  { quote: "L'avenir appartient à ceux qui croient en la beauté de leurs rêves.", author: "Eleanor Roosevelt" },
  { quote: "Qu’est-ce que le génie ? – Avoir un but élevé et vouloir les moyens d’y parvenir.", author: "Friedrich Nietzsche" },
  { quote: "La vie est une pièce de théâtre : ce qui compte, ce n’est pas qu’elle soit longue mais qu’elle soit bien jouée.", author: "Sénèque" },
  { quote: "Autant vaut l’homme qu’il s’estime.", author: "Rabelais" },
  { quote: "Lorsque je me prépare à discuter avec quelqu’un, je consacre un tier du temps à penser à ce que je vais dire et deux tiers à penser à ce que l’autre va me dire.", author: "Abraham Lincoln" },
  { quote: "L'inspiration existe, mais elle doit vous trouver en train de travailler.", author: "Pablo Picasso" },
  { quote: "Je n’ai pas de talent particulier. Je suis seulement passionnément curieux.", author: "Albert Einstein" },
  { quote: "Si je disposais de neuf heures pour abattre un arbre, j’en emploierais six pour affûter ma hache.", author: "Abraham Lincoln" },
  { quote: "Hier est derrière, demain est mystère, et aujourd’hui est un cadeau, c’est pour cela qu’on l’appelle le présent.", author: "Maître Oogway (Dreamworks Animation)" },
  { quote: "La simplicité est la sophistication suprême.", author: "Léonard de Vinci" },
  { quote: "Les folies sont les seules choses qu’on ne regrette jamais.", author: "Oscar Wilde" },
  { quote: "L’amour commence par soi. Lorsque votre relation avec vous-même est fondée sur l’amour et le respect, toutes vos relations changent.", author: "Don Miguel Ruiz" },
  { quote: "Un gramme d’action vaut mieux qu’une tonne de parole.", author: "Ralph Waldo Emerson" },
  { quote: "Cultiver sa différence pour susciter la préférence.", author: "Anonyme" },
  { quote: "Rien n'est particulièrement difficile si vous le découpez en petites tâches.", author: "Henry Ford" },
  { quote: "Le succès est la somme de petits efforts — répétée jour après jour.", author: "Robert Collier" },
  { quote: "Deux routes divergeaient dans un bois, et moi,J’ai pris celle par laquelle on voyage le moins souvent,Et que c’est cela qui a tout changé.", author: "Robert Frost" },
  { quote: "Ce qu’on obtient en atteignant nos objectifs n’est pas aussi important que ce que l’on devient en les atteignant.", author: "Zig Ziglar" },
  { quote: "L’une de mes meilleures décisions, c’est de me faire entourer d’amis qui au lieu de demander 'Pourquoi ?' sont pressés de demander 'Pourquoi pas ?'. Cette attitude est plutôt contagieuse.", author: "Oprah Winfrey" },
  { quote: "L’échec provient plus souvent d’un manque d’énergie que d’un manque d’argent.", author: "Daniel Webster" },
  { quote: "Chaque difficulté rencontrée doit être une occasion de progrès.", author: "Pierre de Coubertin" },
  { quote: "Se lamenter sur le malheur passé, voilà le plus sûr moyen d’en attirer un autre.", author: "William Shakespeare" },
  { quote: "Dans la vie, tout est une affaire de risque. Ce que vous devez vraiment apprendre est comment le gérer.", author: "Reid Hoffman" },
  { quote: "Il vaut mieux être plusieurs sur une bonne affaire que seul sur une mauvaise.", author: "Tristan Bernard" },
  { quote: "Ne cherchez pas la faute, trouvez un remède.", author: "Henry Ford" },
  { quote: "Chaque réussite commence avec la volonté d'essayer.", author: "Auteur inconnu" },
  { quote: "Dites à tout le monde ce que vous voulez faire et quelqu’un vous aidera à l’accomplir.", author: "W. Clement Stone" },
  { quote: "Rien n’est plus dangereux qu’une idée quand on n’a qu’une idée.", author: "Alain (Emile Auguste Chartier)" },
  { quote: "J’ai appris que le courage n’est pas l’absence de peur, mais la capacité à la vaincre.", author: "Nelson Mandela" },
  { quote: "Sans mentir la chose que vous avez à faire, c’est de vous entourer de bons collaborateurs.", author: "Peter Rose" },
  { quote: "Un objectif sans plan s’appelle un vœu.", author: "Antoine de Saint-Exupéry" },
  { quote: "On sait qu’on est sur la bonne voie quand on n’a plus envie de se retourner.", author: "Auteur inconnu" },
  { quote: "Un pessimiste voit la difficulté dans chaque opportunité, un optimiste voit l'opportunité dans chaque difficulté.", author: "Winston Churchill" },
  { quote: "Mieux vaut rater sa chance que de ne pas l’avoir tentée.", author: "Proverbe chinois" },
  { quote: "Ce qui est important est rarement urgent et ce qui est urgent rarement important.", author: "Eisenhower" },
  { quote: "N’attendez pas le jour où vous vous sentirez bien dans votre peau pour vous lancer.", author: "Jerry Porras" },
  { quote: "Assurez-vous d’avoir fini de parler avant que votre interlocuteur ait fini de vous écouter.", author: "Ernest Hemingway" },
  { quote: "La seule personne à qui vous ne devriez jamais croire quand il s’agit d’évaluer vos capacités, c’est vous. Le pire juge de vos capacités, c’est vous. L’auto-évaluation n’est jamais réussie. Lorsque vous êtes le meilleur dans quelque chose, la demande de votre les services se développeront. Les gens veulent embaucher les meilleurs. Ils veulent être associés aux meilleurs.", author: "Mark Cuban" },
  { quote: "Le bonheur est souvent la seule chose qu'on puisse donner sans l'avoir et c'est en le donnant qu'on l'acquiert.", author: "Voltaire" },
  { quote: "Entraînement difficile, guerre facile", author: "Proverbe de la légion étrangère" },
  { quote: "Le temps est ce que nous désirons le plus, mais ce que nous utilisons le moins bien.", author: "William Penn" },
  { quote: "Si vous voulez atteindre un objectif, vous devez voir le résultat dans votre esprit avant de réaliser effectivement votre objectif", author: "Zig Ziglar" },
  { quote: "Un service rendu sans joie n’enrichit ni celui qui le rend, ni celui qui le reçoit. Mais tous les biens et les plaisirs matériels se dissolvent dans le néant face à un service rendu dans un esprit de joie.", author: "Gandhi" },
  { quote: "La porte du changement ne peut s’ouvrir que de l’intérieur.", author: "Jacques Salomé" },
  { quote: "Croyez en vos rêves et ils se réaliseront peut-être. Croyez en vous et ils se réaliseront sûrement.", author: "Martin Luther King" },
  { quote: "La clé dans tout ce que l’on fait, c’est de prioriser. C’est-à-dire de cerner les points importants à traiter pour nous, et de s’y tenir.", author: "Mark Zuckerberg" },
  { quote: "Le secret de la créativité c’est de savoir comment cacher ses sources.", author: "Albert Einstein" },
  { quote: "Le succès n'est pas final, l'échec n'est pas fatal : c'est le courage de continuer qui compte.", author: "Winston Churchill" },
  { quote: "Les éléments essentiels au bonheur dans cette vie sont quelque chose à faire, à aimer et à espérer.", author: "Hector Garcia Puigcerver,\n      Ikigai: le secret japonais d’une vie longue et heureuse" },
  { quote: "Ce qui est dangereux c’est de ne pas évoluer.", author: "Jeff bezos" },
  { quote: "Très souvent un changement de soi, est plus nécessaire qu’un changement de situation.", author: "Théodore Monod" },
  { quote: "Essayez, Essayez, Essayez et continuez d’essayer est la règle qu’il faut suivre pour devenir un expert dans n’importe quel domaine.", author: "W. Clement Stone" },
  { quote: "Soyez réalistes : demandez l’impossible.", author: "Ernesto Che Guevara" },
  { quote: "Les gens qui réussissent sont toujours à la recherche d’opportunités pour aider les autres. Les gens perdants se demandent, Qu’y a t-il pour moi?", author: "Brian Tracy" },
  { quote: "J’ai appris que les erreurs peuvent parfois nous donner plus de leçons que le succès.", author: "Jack Welch" },
  { quote: "L’échec n’est qu’une opportunité pour recommencer la même chose plus intelligemment.", author: "Henry Ford" },
  { quote: "J’ai beaucoup mieux à faire que m’inquiéter de l’avenir : j’ai à le préparer.", author: "Félix-Antoine Savard" },
  { quote: "Vous ne pouvez choisir ni comment mourir, ni quand. Mais vous pouvez décider de comment vous allez vivre maintenant.", author: "Joan Baez" },
  { quote: "La différence entre un rêve et un projet, c'est une date.", author: "Walt Disney" },
  { quote: "Vous ne pouvez pas arrêter les vagues, mais vous pouvez apprendre à surfer.", author: "Joseph Goldstein" },
  { quote: "Prenez soin de vos rêves, ils finiront par prendre soin de vous.", author: "Auteur inconnu" },
  { quote: "Ce qui est criminel, ce n’est pas d’échouer, c’est de manquer d’ambition.", author: "Napoléon Bonaparte" },
  { quote: "Rien ne sert de penser ; il faut réfléchir avant.", author: "Pierre Dac" },
  { quote: "Chaque matin nous renaissons à nouveau. Ce que nous faisons aujourd’hui est ce qui importe le plus.", author: "Bouddha" },
  { quote: "Tu ne changeras jamais ta vie sans changer quelque chose quotidiennement ; le secret du succès se trouve dans la routine de chaque jour.", author: "John C Maxwell" },
  { quote: "Il est toujours trop tôt pour abandonner.", author: "Norman Vincent Peale" },
  { quote: "Au fur et à mesure que je modifie mes pensées, le monde autour de moi se transforme.", author: "Louise L. Hay" },
  { quote: "Si vous voulez réussir dans la vie, regardez simplement ce que tout le monde fait, et faites l’exact opposé.", author: "Earl Nightingale" },
  { quote: "Une décision moyenne qu’on transforme rapidement en action donne souvent des meilleurs résultats qu’une décision parfaite qu’on met plusieurs mois à exécuter.", author: "Lee Iacocca" },
  { quote: "Le grand art, c’est de changer pendant la bataille. Malheur au général qui arrive au combat avec un système.", author: "Napoléon Bonaparte" },
  { quote: "L’échec n’est qu’un changement temporaire de direction qui te remet directement sur le chemin de la réussite.", author: "Dennis Waitle" },
  { quote: "Trop de gens se servent des études comme un ivrogne d’un réverbère : davantage pour s’appuyer que pour s’éclairer.", author: "David Ogilvy" },
  { quote: "Vivre est ce qu’il y a de plus beau au monde, la plupart de gens existent, c’est tout.", author: "Oscar Wilde" },
  { quote: "Gagner n’est pas tout, mais l’effort qu’il faut fournir l’est.", author: "Zig Ziglar" },
  { quote: "Que vous vous pensiez capable de faire quelque chose ou que vous vous en pensiez incapable, vous avez absolument raison.", author: "Henry Ford" },
  { quote: "La vie m’a enseigné au moins une chose : si quelqu’un avance avec confiance en direction de ses rêves et qu’il s’efforce de mener l’existence qu’il a imaginée, il jouira d’une réussite hors du commun.", author: "Henry David Thoreau" },
  { quote: "Le succès, c'est tomber sept fois, se relever huit.", author: "Proverbe japonais" },
  { quote: "Ne craignez pas la perfection, vous n’y parviendrez jamais.", author: "Salvador Dali" },
  { quote: "Il n'y a pas de vent favorable pour celui qui ne sait pas où il va.", author: "Sénèque" },
  { quote: "L'expérience est une lanterne accrochée dans le dos, elle éclaire le chemin déjà parcouru.", author: "Confucius" },
  { quote: "Celui qui a une bonne idée mais ne sait pas la vendre n’est pas plus avancé que celui qui n’en a pas.", author: "Abraham Lincoln" },
  { quote: "La vie, c'est comme une bicyclette, il faut avancer pour ne pas perdre l'équilibre.", author: "Albert Einstein" },
  { quote: "Écrire (prendre des notes), c’est écouter deux fois.", author: "Confucius" },
  { quote: "Ne jamais parler de soi aux autres et leur parler toujours d’eux-mêmes ; c’est tout l’art de plaire. Chacun le sait et tout le monde l’oublie.", author: "Les frères Goncourt" },
  { quote: "La chance ne sourit qu’aux esprit bien préparés.", author: "Louis Pasteur" },
  { quote: "Votre temps est limité, ne le gâchez pas en vivant la vie de quelqu'un d'autre.", author: "Steve Jobs" },
  { quote: "Quand on ose, on se trompe souvent. Quand on n’ose pas, on se trompe toujours.", author: "Romain Rolland" },
  { quote: "Le succès est de vous aimer, d’aimer ce que vous faites, et d’aimer la façon dont vous le faites.", author: "Maya Angelou" },
  { quote: "La vente commence quand le client dit non.", author: "Jean Saint-Mleux" },
  { quote: "Quand on ne sait pas où l’on va, tous les chemins mènent nulle part.", author: "Henry Kissinger" },
  { quote: "Vous ne trouverez jamais ce que vous ne cherchez pas.", author: "Confucius." },
  { quote: "L’homme ordinaire ne se préoccupe que de passer le temps, l’homme de talent que de l’employer.", author: "Arthur Schopenhauer" },
  { quote: "L’énergie et l’obstination viennent à bout de toutes les résistances.", author: "Benjamin Franklin" },
  { quote: "Faites que le rêve dévore votre vie afin que la vie ne dévore pas votre rêve.", author: "Antoine de Saint-Exupéry" },
  { quote: "Si vous attendez pour agir, tout ce que vous gagnerez avec le temps, c’est de l’âge.", author: "Brian Tracy" },
  { quote: "Vous êtes né pour gagner, mais pour être un gagnant, vous devez planifier pour gagner, se préparer à gagner, et s’attendre à gagner.", author: "Zig Ziglar" },
  { quote: "Le plus grand risque est de ne prendre aucun risque. Dans un monde qui change vraiment vite, la seule stratégie qui échoue est de ne prendre aucun risque.", author: "Mark Zuckerberg" },
  { quote: "Si vous faites ce que vous avez toujours fait, vous obtiendrez ce que vous avez toujours obtenu.", author: "Anthony Robbins" },
  { quote: "La règle, c’est que le général qui triomphe est celui qui est le mieux informé.", author: "Sun Tzu" },
  { quote: "Plus on connaît, plus on aime.", author: "Leonard de Vinci" },
  { quote: "On a tous une double vie, une pour la lumière et une autre qu’on garde dans l’ombre", author: ". Bruce Wayne" },
  { quote: "Plus vous aidez les gens à obtenir ce qu’il désirent et plus vous avez de succès.", author: "Zig Ziglar" },
  { quote: "Vous pouvez vaincre presque n’importe quelle crainte si vous vous décidez à le faire.", author: "Dale Carnegie" },
  { quote: "Ce que nous devons apprendre à faire, nous l’apprenons en le faisant", author: "Aristote" },
  { quote: "Il n’est pas de vent favorable pour celui qui ne sait où il va.", author: "Sénèque" },
  { quote: "Qui veut faire quelque chose trouve un moyen. Qui ne veut rien faire trouve un prétexte.", author: "Anonyme" },
  { quote: "Le bateau est plus en sécurité quand il est au port mais ce n’est pas pour cela qu’ont été construits les bateaux.", author: "Paulo Coelho" },
  { quote: "Vous êtes le maître de votre destin, le capitaine de votre âme.", author: "William Ernest Henley" },
  { quote: "Un instant de colère peut détruire des années de patience.", author: "Shantideva" },
  { quote: "Plutôt que de penser à ce que tu n’as pas, pense à ce que tu peux faire avec ce que tu as.", author: "Ernest Hemingway" },
  { quote: "La meilleure manière de prédire l'avenir est de le créer.", author: "Peter Drucker" },
  { quote: "Si tu changes tes habitudes, tu changes qui tu es.", author: "Marshall Sylver" },
  { quote: "L'éducation est l'arme la plus puissante pour changer le monde.", author: "Nelson Mandela" },
  { quote: "Créer des opportunités signifie regarder là où les autres ne sont pas.", author: "Mark Cuban" },
  { quote: "Si vous ne pouvez pas faire de grandes choses, faites de petites choses de façon grandioses.", author: "Napoleon Hill" },
  { quote: "Les gagnants cherchent des moyens, les perdants des excuses.", author: "Franklin Roosevelt" },
  { quote: "L’ouverture d’esprit n’est pas une fracture du crâne.", author: "Pierre Desproges" },
  { quote: "Être attentif à ce que l’autre dit n’est pas suffisant, c’est écouter son âme qu’il te faut.", author: "Marc Aurèle" },
  { quote: "Regardez ce que font les idiots et faites le contraire.", author: "Robert T. Kiyosaki" },
  { quote: "L’action seule suffit pour mettre à bout tout doute quelle que soit sa nature.", author: "Thomas Carlyle" },
  { quote: "La seule chose qui puisse vous empêcher d'atteindre vos rêves, c'est vous-même.", author: "Tom Bradley" },
  { quote: "Il n'y a pas de réussite facile ni d'échecs définitifs.", author: "Marcel Proust" },
  { quote: "Pour être irremplaçable, il faut être différent.", author: "Coco Chanel" },
  { quote: "Une opportunité est manquée par beaucoup de gens parce qu’elle est souvent cachée dans la vue d’ensemble et ressemble au travail.", author: "Thomas Edison" },
  { quote: "Le but de la vie est le développement personnel. Parvenir à une parfaite réalisation de sa nature, c’est pour cela que nous sommes tous ici.", author: "Oscar Wilde" },
  { quote: "Il faut rêver la perfection et s’accommoder de l’imparfait.", author: "Henri-Frédéric Amiel" },
  { quote: "Choisissez un travail que vous aimez et vous n’aurez pas à travailler un seul jour de votre vie.", author: "Confucius" },
  { quote: "Se concentrer sur une chose à la fois peut être le facteur le plus important pour atteindre le flow.", author: "Hector Garcia Puigcerver, Ikigai: le secret japonais d’une vie longue et heureuse" },
  { quote: "N’acceptez jamais la défaite, vous êtes peut-être à un pas de la réussite.", author: "Jack E. Addington" },
  { quote: "En ce moment, beaucoup de gens ont renoncé à vivre. Ils ne s’ennuient pas, ils ne pleurent pas, ils se contentent d’attendre que le temps passe. Ils n’ont pas accepté les défis de la vie et elle ne les défie plus.", author: "Paulo Coelho" },
  { quote: "L’éducation formelle vous fera un salarié, l’auto-éducation vous fera un riche.", author: "Jim Rohn" },
  { quote: "N’ayez pas peur d’être différent, ayez peur d’être comme tout le monde." },
  { quote: "Méritez votre statut de leader chaque jour.", author: "Michael Jordan" },
  { quote: "Faites toujours de votre mieux. Ce que vous plantez maintenant, vous le récolterez plus tard.", author: "Og Mandino" },
  { quote: "Il n’existe rien de constant si ce n’est le changement.", author: "Bouddha" },
  { quote: "Au lieu de vous demander quand seront vos prochaines vacances, peut-être que vous devriez construire une vie dans laquelle vous n’avez pas besoin de vous échapper.", author: "Seth Godin" },
  { quote: "Chaque jour est une nouvelle opportunité.", author: "Auteur inconnu" },
  { quote: "Pensez grand et n’écoutez pas les gens qui vous disent que ce n’est pas réalisable. La vie est trop courte pour penser petit.", author: "Tim Ferriss" },
  { quote: "Si vous voulez changer votre vie, la première chose à faire est d’être déraisonnable. Celui qui change le monde n’est pas raisonnable, il adapte le monde à sa vision des choses.", author: "Anthony Robbins" },
  { quote: "Ce que l'esprit peut concevoir et croire, il peut l'accomplir.", author: "Napoléon Hill" },
  { quote: "Le génie, c’est Dieu qui le donne, mais le talent nous regarde.", author: "Gustave Flaubert" },
  { quote: "Rien n'est impossible, seules les limites de nos esprits définissent certaines choses comme inconcevables.", author: "Marc Lévy" },
  { quote: "La réussite est une somme de petits efforts répétés jour après jour.", author: "Robert Collier" },
  { quote: "Soyez vous-même, tous les autres sont déjà pris.", author: "Oscar Wilde" },
  { quote: "À long terme, on ne progresse qu’à condition d’avoir autour de soi des gens d’exception.", author: "Mark Zuckerberg" },
  { quote: "Le talent c’est d’avoir envie de faire quelque chose.", author: "Jacques Brel" },
  { quote: "Celui qui ne sait pas sourire ne doit pas ouvrir boutique.", author: "Proverbe chinois" },
  { quote: "Je travaille à être heureux: c’est le plus beau des métiers.", author: "Roland de Lassus" },
  { quote: "Quand vous avez fini de changer, vous êtes fini.", author: "Benjamin Franklin" },
  { quote: "Aucun de nous, en agissant seul, ne peut atteindre le succès.", author: "Nelson Mandela" },
  { quote: "Les gagnants trouvent des moyens, les perdants des excuses.", author: "Franklin D. Roosevelt" },
  { quote: "Ce sont les pensées d’un Homme qui déterminent sa vie.", author: "Marc Aurèle" },
  { quote: "Celui qui n’a jamais commis d’erreurs n’a jamais tenté d’innover.", author: "Albert Einstein" },
  { quote: "Ne vous plaignez jamais du client difficile car il est cause de vos progrès. traitez les autres mieux encore : ils sont les raisons de vos bénéfices.", author: "Auguste Detoeuf" },
  { quote: "Quand vous avez 10 000 personnes qui essaient de faire la même chose, pourquoi voudriez-vous être le numéro 10 001?", author: "Mark Cuban" },
  { quote: "Il est sage de persuader les gens de faire des choses et de les amener à penser que l’idée venait d’eux.", author: "Nelson Mandela" },
  { quote: "Qu’il est dur d’échouer, mais le pire est de n’avoir jamais tenté de réussir.", author: "Franklin Roosevelt" },
  { quote: "Le bonheur n’est pas un objectif, c’est un sous-produit.", author: "Eleanor Roosevelt" },
  { quote: "Il n’y a qu’un patron : le client. Et il peut licencier tout le personnel, depuis le directeur jusqu’à l’employé, tout simplement en allant dépenser son argent ailleurs.", author: "Sam Walton" },
  { quote: "La manière d’accélérer votre succès, c’est de doubler votre taux d’échec.", author: "Thomas J. Watson" },
  { quote: "L’objectif de toute éducation devrait être de projeter chacun dans l’aventure d’une vie à découvrir, à orienter, à construire.", author: "Albert Jacquard" },
  { quote: "La logique vous mènera d'un point A à un point B. L'imagination vous mènera partout.", author: "Albert Einstein" },
  { quote: "Le courage n'est pas l'absence de peur, mais la capacité de vaincre ce qui fait peur.", author: "Nelson Mandela" },
  { quote: "Le succès n’est pas ce que vous avez, mais plutôt qui vous êtes.", author: "Bo Bennet" },
  { quote: "Commencez par faire ce qui est nécessaire, puis ce qui est possible, et soudain vous ferez l'impossible.", author: "Saint François d'Assise" },
  { quote: "Rien de grand ne s’est accompli sans passion.", author: "Hegel" },
  { quote: "Pour donner un sens à sa vie, il suffit d’aider une seule personne à supporter le fardeau de la sienne", author: "Ralph Waldo Emerson" },
  { quote: "Vous avez très peu de temps à vivre alors ne passez pas votre vie à vivre le rêve d’une autre personne.", author: "Steve Jobs" },
  { quote: "Le diplôme est l’ennemi mortel de la culture.", author: "Paul Valéry" },
  { quote: "Pour réaliser une chose vraiment extraordinaire, commencez par la rêver.", author: "Walt Disney" },
  { quote: "Ne laisse jamais personne te dire ce dont tu n’es pas capable. C’est à toi de choisir et de vivre ta vie.", author: "Laurent Gounelle" },
  { quote: "Ce n’est pas d’où vous venez qui compte, mais où vous allez.", author: "Ella Fitzgerald" },
  { quote: "Confronté à la roche, le ruisseau l’emporte toujours, non par la force, mais par la persévérance.", author: "Confucius" },
  { quote: "Peu importe qui vous êtes ou qui vous avez été, vous pouvez être qui vous voulez.", author: "W. Clement Stone" },
  { quote: "Toutes les richesses ont leur origine dans l’esprit. La richesse est dans les idées — pas dans l’argent.", author: "Robert Collier" },
  { quote: "Qui cherche à plaire à tous ne plaît à personne.", author: "Jean-Baptiste Rousseau" },
  { quote: "C’est effrayant de vivre avec des gens qui vous connaissent. Ils vous empêchent de changer en ne s’apercevant pas que vous êtes un autre.", author: "Robert Charbonneau" },
  { quote: "Avouez vos petits défauts si vous voulez persuader que vous n’en avez pas de grands.", author: "La Rochefoucauld" },
  { quote: "Il faut toujours viser la lune, car même en cas d’échec on atterrit dans les étoiles", author: "Oscar Wilde" },
  { quote: "Le sens de la vie, c’est d’apprendre à  être bien, au-delà de ce que l’on possède, des objets ou des personnes qui nous donnent du plaisir, des événements qui surviennent. C’est de découvrir que le bonheur et le malheur sont à l’intérieur de nous, et non dans les choses ou les événements extérieurs.", author: "Frédéric Lenoir" },
  { quote: "On ne voit bien qu'avec le cœur. L'essentiel est invisible pour les yeux.", author: "Antoine de Saint-Exupéry" },
  { quote: "C’est aujourd’hui que commence le reste de ta vie.", author: "Dale Carnegie" },
  { quote: "Porter son attention au présent ce n’est pas nier ce qui est nécessaire ; c’est reconnaître l’essentiel.", author: "Eckhart Tolle" },
  { quote: "Le plus grand échec est de ne pas avoir le courage d’oser.", author: "L’Abbé Pierre" },
  { quote: "Vis maintenant ! Risque-toi aujourd’hui ! Agis tout de suite! Ne te laisse pas mourir lentement ! Ne te prive pas d’être heureux !", author: "Pablo Neruda" },
  { quote: "Personne n’est trop vieux pour se fixer un nouvel objectif ou réaliser de nouveaux rêves.", author: "Les Brown" },
  { quote: "100% des choses qu’on ne tente pas échouent.", author: "Wayne Gretzky" },
  { quote: "Un sourire ne coûte rien mais il rapporte beaucoup ; il enrichit celui qui le reçoit sans appauvrir celui qui le donne.", author: "Dale Carnegie" },
  { quote: "La volonté forte est admirée de tout le monde parce que personne ne l’a et parce que chacun se dit que, s’il l’avait, il n’y aurait plus de limite pour lui.", author: "Friedrich Nietzsche" },
  { quote: "L'optimisme est la foi qui mène à la réussite.", author: "Helen Keller" },
];

export default quotes;
